"""Agent_Synthesizer — aggregates rubric scores into a disposition and renders
the final Markdown evaluation memorandum. This stage is deterministic
(pure computation + templating) regardless of whether a live LLM is
configured, since it only combines outputs already produced by earlier
agents — no new judgement calls are needed here."""

from __future__ import annotations
from datetime import datetime, timezone

from agents.schemas import (
    ParsedSections,
    DiscrepancyMatrix,
    RubricAudit,
    AuditReport,
    TraceStep,
)

STATUS_TAG = {
    "high": "🔴",
    "medium": "🟠",
    "low": "🟡",
}


def _disposition(score: float) -> str:
    if score >= 85:
        return "Ready for Defense"
    if score >= 70:
        return "Conditional Pass with Minor Revisions"
    return "Requires Major Structural Revision"


def _score_tag(score: float) -> str:
    if score >= 85:
        return "✅"
    if score >= 70:
        return "🟠"
    return "🔴"


def _render_markdown(
    parsed: ParsedSections,
    discrepancy: DiscrepancyMatrix,
    audit: RubricAudit,
    aggregate_score: float,
    disposition: str,
) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []
    lines.append("# Mentor Evaluation Memorandum")
    lines.append(f"*Generated {ts} — Multimodal-MentorAgent v1.0*")
    lines.append("")
    lines.append(f"## Overall Disposition: {_score_tag(aggregate_score)} **{disposition}**")
    lines.append(f"**Aggregate Score: {aggregate_score:.1f} / 100**")
    lines.append("")

    lines.append("## Metric Summary Table")
    lines.append("")
    lines.append("| Rubric | Score | Status |")
    lines.append("|---|---:|:---:|")
    for r in audit.rubric_scores:
        lines.append(f"| {r.rubric} | {r.score:.1f} | {_score_tag(r.score)} |")
    lines.append("")

    lines.append("## Multimodal Alignment Diagnostic Box")
    lines.append("")
    lines.append(f"> **Alignment Score:** {discrepancy.alignment_score:.1f} / 100")
    lines.append(f"> {discrepancy.summary}")
    lines.append(">")
    if discrepancy.items:
        for item in discrepancy.items:
            tag = STATUS_TAG.get(item.severity, "⚪")
            kind = "Unreferenced Visual Block" if item.type == "unreferenced_visual_block" else "Hallucinated Pipeline Claim"
            lines.append(f"> {tag} **{kind}** ({item.severity}): {item.description}")
    else:
        lines.append("> ✅ No discrepancies detected between the diagram and the written methodology.")
    lines.append("")

    lines.append("## Section-by-Section Actionable Feedback")
    lines.append("")
    for fb in audit.section_feedback:
        lines.append(f"### {fb.section}")
        lines.append(f"- **Current Issue:** {fb.current_issue}")
        lines.append(f"- **Recommended Revision:** {fb.recommended_revision}")
        lines.append("")

    lines.append("## Rubric Detail")
    lines.append("")
    for r in audit.rubric_scores:
        lines.append(f"**{r.rubric} — {r.score:.1f}/100**")
        for c in r.comments:
            lines.append(f"- {c}")
        lines.append("")

    lines.append("---")
    lines.append(
        "*This memorandum was generated by an AI-assisted multi-agent review pipeline "
        "and is intended to accelerate, not replace, the industry mentor's own judgement. "
        "Final assessment decisions rest with the human mentor.*"
    )

    return "\n".join(lines)


def run_agent_synthesizer(
    parsed: ParsedSections,
    discrepancy: DiscrepancyMatrix,
    audit: RubricAudit,
) -> tuple[AuditReport, TraceStep]:
    aggregate_score = sum(r.score for r in audit.rubric_scores) / len(audit.rubric_scores)
    disposition = _disposition(aggregate_score)
    markdown_report = _render_markdown(parsed, discrepancy, audit, aggregate_score, disposition)

    report = AuditReport(
        aggregate_score=aggregate_score,
        disposition=disposition,
        rubric_scores=audit.rubric_scores,
        discrepancy_matrix=discrepancy,
        section_feedback=audit.section_feedback,
        markdown_report=markdown_report,
    )

    trace = TraceStep(
        agent="Agent_Synthesizer",
        thought="Aggregate the four rubric scores into a single disposition and render the final Markdown memorandum.",
        action="mean(rubric_scores) -> disposition; _render_markdown(...)",
        observation=f"aggregate_score={aggregate_score:.1f}, disposition='{disposition}'.",
    )
    return report, trace
